import { VideoRecord } from "@/lib/mvp/types";

/**
 * Escape Markdown special characters
 */
function escapeMarkdown(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

/**
 * Convert video summary to Markdown format
 */
export function exportToMarkdown(video: VideoRecord): string {
  if (!video.summary) {
    throw new Error("Video has no summary to export");
  }

  const summary = video.summary;
  const date = new Date().toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  let markdown = `# ${escapeMarkdown(video.title)}\n\n`;
  markdown += `**Date:** ${video.date}\n`;
  markdown += `**Duration:** ${video.duration}\n`;
  markdown += `**Source:** ${video.sourceType}\n`;
  markdown += `**Summarized:** ${date}\n\n`;

  markdown += `## Executive Summary\n\n`;
  markdown += `${summary.executiveSummary}\n\n`;

  if (summary.keyTakeaways && summary.keyTakeaways.length > 0) {
    markdown += `## Key Takeaways\n\n`;
    summary.keyTakeaways.forEach((takeaway) => {
      markdown += `- ${escapeMarkdown(takeaway)}\n`;
    });
    markdown += `\n`;
  }

  if (summary.actionItems && summary.actionItems.length > 0) {
    markdown += `## Action Items\n\n`;
    summary.actionItems.forEach((item) => {
      const priority = item.priority || "Medium";
      const assignee = item.assignee ? ` (${item.assignee})` : "";
      markdown += `- **[${priority}]** ${escapeMarkdown(item.text)}${assignee}\n`;
    });
    markdown += `\n`;
  }

  markdown += `---\n\n`;
  markdown += `*Generated by VideoSum using AI summarization*\n`;

  return markdown;
}

/**
 * Trigger browser download of Markdown file
 */
export function downloadMarkdown(video: VideoRecord): void {
  const markdown = exportToMarkdown(video);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  // Create filename from video title (sanitized)
  const filename =
    video.title
      .replace(/[^a-z0-9]/gi, "-")
      .replace(/-+/g, "-")
      .toLowerCase()
      .slice(0, 50) + "-summary.md";

  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Copy Markdown to clipboard
 */
export async function copyMarkdownToClipboard(
  video: VideoRecord,
): Promise<void> {
  const markdown = exportToMarkdown(video);
  await navigator.clipboard.writeText(markdown);
}
